// <auto-generated />
using System;
using PropertySystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PropertySystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250815174951_RolesSystem")]
    partial class RolesSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropertySystem.Domain.PaymentIntentions.PaymentIntention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_payment_intention");

                    b.ToTable("payment_intention", (string)null);
                });

            modelBuilder.Entity("PropertySystem.Domain.Users.SysRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Registered"
                        });
                });

            modelBuilder.Entity("PropertySystem.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("BusinessUnit")
                        .HasColumnType("int")
                        .HasColumnName("business_unit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("identification");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("identity_id");

                    b.Property<DateTime>("InactivationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("inactivation_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.Property<Guid>("Role")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("second_name");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.HasIndex("IdentityId")
                        .HasDatabaseName("ix_user_identity_id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("SysRoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int")
                        .HasColumnName("roles_id");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("users_id");

                    b.HasKey("RolesId", "UsersId")
                        .HasName("pk_sys_role_user");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_sys_role_user_users_id");

                    b.ToTable("sys_role_user", (string)null);
                });

            modelBuilder.Entity("PropertySystem.Domain.PaymentIntentions.PaymentIntention", b =>
                {
                    b.OwnsOne("PropertySystem.Domain.PaymentIntentions.Client", "Client", b1 =>
                        {
                            b1.Property<Guid>("PaymentIntentionId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("client_code");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("client_email");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("client_name");

                            b1.Property<string>("Nit")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("client_nit");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("client_phone");

                            b1.HasKey("PaymentIntentionId");

                            b1.ToTable("payment_intention");

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentionId")
                                .HasConstraintName("fk_payment_intention_payment_intention_id");
                        });

                    b.OwnsOne("PropertySystem.Domain.PaymentIntentions.DateRange", "Dates", b1 =>
                        {
                            b1.Property<Guid>("PaymentIntentionId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("created_at");

                            b1.Property<DateTime?>("ExpiresAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("expires_at");

                            b1.HasKey("PaymentIntentionId");

                            b1.ToTable("payment_intention");

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentionId")
                                .HasConstraintName("fk_payment_intention_payment_intention_id");
                        });

                    b.OwnsOne("PropertySystem.Domain.PaymentIntentions.DocumentInformation", "DocumentInformation", b1 =>
                        {
                            b1.Property<Guid>("PaymentIntentionId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<bool?>("CollectShipping")
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("bit")
                                .HasColumnName("collect_shipping");

                            b1.Property<string>("DynamicValue")
                                .HasMaxLength(2147483647)
                                .IsUnicode(false)
                                .HasColumnType("varchar(max)")
                                .HasColumnName("dynamic_value");

                            b1.Property<bool?>("SingleUse")
                                .HasColumnType("bit")
                                .HasColumnName("single_use");

                            b1.Property<int>("StatusEmail")
                                .HasColumnType("int")
                                .HasColumnName("status_email");

                            b1.Property<string>("TransactionId")
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("transaction_id");

                            b1.Property<Guid>("User")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("user");

                            b1.HasKey("PaymentIntentionId");

                            b1.HasIndex("User")
                                .HasDatabaseName("ix_payment_intention_user");

                            b1.ToTable("payment_intention");

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentionId")
                                .HasConstraintName("fk_payment_intention_payment_intention_id");

                            b1.HasOne("PropertySystem.Domain.Users.User", null)
                                .WithMany()
                                .HasForeignKey("User")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("fk_payment_intention_user_user");
                        });

                    b.OwnsOne("PropertySystem.Domain.PaymentIntentions.Key", "Key", b1 =>
                        {
                            b1.Property<Guid>("PaymentIntentionId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("App")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("app");

                            b1.Property<int>("BusinessUnit")
                                .HasColumnType("int")
                                .HasColumnName("business_unit");

                            b1.Property<string>("Document")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("document");

                            b1.Property<string>("DocumentPayment")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("document_payment");

                            b1.Property<int>("Provider")
                                .HasColumnType("int")
                                .HasColumnName("provider");

                            b1.Property<string>("ProviderProduct")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("provider_product");

                            b1.HasKey("PaymentIntentionId");

                            b1.ToTable("payment_intention");

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentionId")
                                .HasConstraintName("fk_payment_intention_payment_intention_id");
                        });

                    b.OwnsOne("PropertySystem.Domain.PaymentIntentions.Money", "Money", b1 =>
                        {
                            b1.Property<Guid>("PaymentIntentionId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("money_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(false)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("money_currency");

                            b1.HasKey("PaymentIntentionId");

                            b1.ToTable("payment_intention");

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentionId")
                                .HasConstraintName("fk_payment_intention_payment_intention_id");
                        });

                    b.OwnsOne("PropertySystem.Domain.PaymentIntentions.Session", "Session", b1 =>
                        {
                            b1.Property<Guid>("PaymentIntentionId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("IdSession")
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("id_session");

                            b1.Property<string>("TokenSession")
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("token_session");

                            b1.HasKey("PaymentIntentionId");

                            b1.ToTable("payment_intention");

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentionId")
                                .HasConstraintName("fk_payment_intention_payment_intention_id");
                        });

                    b.OwnsOne("PropertySystem.Domain.PaymentIntentions.Supplier", "Supplier", b1 =>
                        {
                            b1.Property<Guid>("PaymentIntentionId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("SupplierMessage")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("supplier_message");

                            b1.HasKey("PaymentIntentionId");

                            b1.ToTable("payment_intention");

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentionId")
                                .HasConstraintName("fk_payment_intention_payment_intention_id");
                        });

                    b.OwnsOne("PropertySystem.Domain.PaymentIntentions.Urls", "Urls", b1 =>
                        {
                            b1.Property<Guid>("PaymentIntentionId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("ImageUrl")
                                .HasMaxLength(400)
                                .IsUnicode(false)
                                .HasColumnType("varchar(400)")
                                .HasColumnName("image_url");

                            b1.Property<string>("RedirectUrl")
                                .HasMaxLength(400)
                                .IsUnicode(false)
                                .HasColumnType("varchar(400)")
                                .HasColumnName("redirect_url");

                            b1.Property<string>("Url")
                                .HasMaxLength(400)
                                .IsUnicode(false)
                                .HasColumnType("varchar(400)")
                                .HasColumnName("url");

                            b1.HasKey("PaymentIntentionId");

                            b1.ToTable("payment_intention");

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentionId")
                                .HasConstraintName("fk_payment_intention_payment_intention_id");
                        });

                    b.Navigation("Client")
                        .IsRequired();

                    b.Navigation("Dates")
                        .IsRequired();

                    b.Navigation("DocumentInformation")
                        .IsRequired();

                    b.Navigation("Key")
                        .IsRequired();

                    b.Navigation("Money")
                        .IsRequired();

                    b.Navigation("Session")
                        .IsRequired();

                    b.Navigation("Supplier")
                        .IsRequired();

                    b.Navigation("Urls")
                        .IsRequired();
                });

            modelBuilder.Entity("PropertySystem.Domain.Users.User", b =>
                {
                    b.OwnsOne("PropertySystem.Domain.Users.UserContact", "UserContact", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(200)
                                .IsUnicode(false)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("user_contact_address");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(15)
                                .IsUnicode(false)
                                .HasColumnType("varchar(15)")
                                .HasColumnName("user_contact_phone");

                            b1.HasKey("UserId");

                            b1.ToTable("user");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_user_user_id");
                        });

                    b.Navigation("UserContact")
                        .IsRequired();
                });

            modelBuilder.Entity("SysRoleUser", b =>
                {
                    b.HasOne("PropertySystem.Domain.Users.SysRole", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_role_user_sys_role_roles_id");

                    b.HasOne("PropertySystem.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_role_user_user_users_id");
                });
#pragma warning restore 612, 618
        }
    }
}
